default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: color_matcher_development
  username: postgres
  password: JYUqf2yNmbxAYM1q1evqLKmstL2X0rGh
  host: localhost

test:
  <<: *default
  database: color_matcher_test
  username: postgres
  password: JYUqf2yNmbxAYM1q1evqLKmstL2X0rGh
  host: localhost
  
production:
  <<: *default
  database: color_matcher
  username: color_matcher_user
  password: <%= ENV["DB_PASSWORD"] %>
  host: dpg-d4d2a3ripnbc739pot90-a.singapore-postgres.render.com
  port: 5432
  sslmode: require

